### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by Gouravmoy** [VivekBasidoni/RCPDataComparator#58]
Error Handling through out the application

**Comment by Gouravmoy** [comment]
Completed all.. Need do check again

**Comment by Gouravmoy** [comment]
Done

**Comment by VivekBasidoni** [comment]
Added job level error handling.

**Comment by VivekBasidoni** [comment]
Getting error in generate CSV when data has special character (,) .

**Comment by VivekBasidoni** [comment]
Data reliability % not working as expected

**Comment by VivekBasidoni** [comment]
1#~1#=customer_id|1|1|true#~store_id|1|1|true#~first_name|MARY,,ヴィヴェック|MARY,,"??????"|false#~last_name|SMITH,M|SMITH,M|true#~email|MARY.SMITH@sakilacustomer.org|MARY.SMITH@sakilacustomer.org|true#~address_id|5|5|true#~active|1|1|true#~create_date|14-02-2006 22:04:36|14-02-2006 22:04:36|true#~last_update|15-02-2006 04:57:20|23-09-2016 16:30:56|false

read database does not support foreign elements

**Comment by Gouravmoy** [comment]
- [ ] Getting error in generate CSV when data has special character (,) .
- [ ] Data reliability % not working as expected
- [ ] Read database does not support foreign characters

**Comment by Gouravmoy** [comment]
?useUnicode=true&characterEncoding=UTF-8 for defectRead database does not support foreign characters

**Comment by Gouravmoy** [comment]
Data reliability % not working as expected - Logic has to bechaged
